### ISSUE TITLE
Support other compression types than gz

### ISSUE THREAD

**Issue by mbanck** [pgstef/check_pgbackrest#16]
pgBackRest supports at least .gz, .bz2 and .zst as compression types, but it seems `check_pgbackrest` only supports `.gz`? From `get_archived_wal_list()`:

```
    my $suffix = ".gz";
```

**Comment by pgstef** [comment]
Hi,
This has been fixed in this [PR](https://github.com/pgstef/check_pgbackrest/pull/12) and will be available in the next release.
Kind regards

**Comment by pgstef** [comment]
[v2.0](https://github.com/pgstef/check_pgbackrest/releases/tag/REL2_0) have been released and should solve this issue.
Don't hesitate to reopen it the request isn't answered.
Kind regards
