### ISSUE TITLE
Service archive Azure Storage account support

### ISSUE THREAD

**Issue by mroisset** [pgstef/check_pgbackrest#18]
Hello,

Have you planned to add Azure support for archives ?

Thanks

**Comment by pgstef** [comment]
Hi,

Yes. [v2](https://github.com/pgstef/check_pgbackrest/tree/dev-release-2-0) will use pgBackRest internal commands to check the repository content and should then work with Azure too.

You can already try with that dev release to make sure it would work for you.

Kind regards

**Comment by mroisset** [comment]
Just tested dev release and it works.

Merci
