### ISSUE TITLE
archives service will not work if the WAL files are not compressed

### ISSUE THREAD

**Issue by jpguerard** [pgstef/check_pgbackrest#26]
When running check_pgbackrest with the archives services on an uncompressed WAL (`--compress-type=none`), the WAL files will not be found.

This could be fixed by replacing:

`my $suffix = "\.(gz|lz4|zst|xz|bz2)";`

By:

`my $suffix = "(\.(gz|lz4|zst|xz|bz2))?";`

**Comment by pgstef** [comment]
Hi,

Closing this issue since this feature has been released in version [2.2](https://github.com/pgstef/check_pgbackrest/releases/tag/REL2_2).

Kind Regards
