### ISSUE TITLE
Feature: zabbix integration

### ISSUE THREAD

**Issue by klepek** [pgstef/check_pgbackrest#31]
Hi,

I have prepared pull request with zabbix integration (#30).

If you agree with this, please review and let me know if there is any change required.

Regards,
Jan Klepek

**Comment by goat90** [comment]
It's a great functionality!
I am waiting for implementation.

**Comment by pgstef** [comment]
Hi,

I'm happy to learn that the tool (using the json output format) is working with Zabbix.

Unfortunately, I don't have any knowledge of that tool and I wasn't able to implement it in the test suite yet. So, currently, I'm not open to support any code I can't test.

I'll have a look at the PR though and see if there's any code impact to accept it.

That being said, if you have any good resource to show how to use zabbix docker containers to monitor PG instances, I'd be willing to give it another try. (The test suite code is based on docker and ansible, can be found in the test directory)

Kind Regards

**Comment by goat90** [comment]
This could be helpfull to prepare a test server:
https://techexpert.tips/zabbix/zabbix-docker-installation-ubuntu-linux/
Official documentation:
https://www.zabbix.com/documentation/current/en/manual/installation/containers

Agent installation:
https://www.codesie.ch/en/wiki/ansible/install-zabbix-agent

Best Regards
