### ISSUE TITLE
Version pgbackrest compatible avec check_pgbackrest 2.3

### ISSUE THREAD

**Issue by ccavallie** [pgstef/check_pgbackrest#34]
Bonjour,
Est-ce que la version 2.33 est compatible avec la version 2.29 de pgbackrest?
Merci d'avance pour votre réponse

**Comment by pgstef** [comment]
Bonjour,

Je présume que vous parlez de la dernière version de check_pgbackrest : `2.3` sortie en mai dernier ?

La version minimum de pgBackRest supportée est actuellement la [`2.33`](https://github.com/pgbackrest/pgbackrest/releases/tag/release%2F2.33) sortie en avril 2021.

Pour retrouver les derniers correctifs de check_pgbackrest, vous pouvez vous reporter au [changelog](https://github.com/pgstef/check_pgbackrest/blob/REL2_3/CHANGELOG.md). 
- Depuis février 2021 et check_pgbackrest 2.0, la version minimum de pgBackRest supportée était la 2.32.
- Depuis check_pgbackrest 2.1, la version minimum de pgBackRest est 2.33.
- Pour bénéficier des dernières fonctionnalités de check_pgbackrest 2.2, il faut être sur pgBackRest 2.36 minimum (parue en novembre 2021).

pgBackRest 2.29 date de fin août 2020 et devrait selon moi être mis à jour rapidement au vu des correctifs et nouvelles fonctionnalités parues depuis.

Cordialement,

**Comment by ccavallie** [comment]
Merci pour cette réponse
