### ISSUE TITLE
RHEL 7 common repository (EOL) users might encounter "FATAL: Unsupported pgBackRest version."

### ISSUE THREAD

**Issue by m-borger** [pgstef/check_pgbackrest#38]
## Not a bug
This issue is not a bug report but merely a heads-up to RHEL 7 repository users.

## Symptoms
When updating from the [PostgreSQL Common Repository](https://yum.postgresql.org/common/redhat/rhel-7-x86_64/repoview/) after 2024-07-05 the `check_pgbackrest` program will show this error message:
`FATAL: Unsupported pgBackRest version.`

## Cause
Package `nagios-plugins-pgbackrest-2.4-1PGDG.rhel7` was added on 2024-07-06 and supports only version 2.52 and above, as stated correctly in the README:
_check_pgbackrest is designed to monitor pgBackRest (2.52 and above) backups from Nagios._

The last version of pgbackrest added to the common repository is 2.51 (`pgbackrest-2.51-2PGDG.rhel7`) and, according to the [EOL announcement for RHEL 7](https://yum.postgresql.org/news/rhel7-end-of-life) this will be the final version in this repo:
_The PostgreSQL RPM repository will no longer provide updates to any packages except PostgreSQL RPMs as of 8 July 2024. This means no extensions or no other software will receive any updates even for security fixes._

This seems to leave the pgbackrest / nagios-plugins-pgbackrest combination in an incompatible state in this repository.

## Solution
Of course the best solution is to upgrade the OS of those systems as soon as possible, but until then this issue might guide users to the cause of the problem.

## Workaround(s)
This depends on the way you manage the updates of your OS. Fixating the use of version `nagios-plugins-pgbackrest-2.3-1.rhel7.noarch` solves the problem.
First aid (until the next update) to this problem could be:
```bash
yum -y downgrade nagios-plugins-pgbackrest
```

**Comment by pgstef** [comment]
Hi,

Thanks for the report.

RHEL7 is indeed EOL, so I don't maintain it for check_pgbackrest either. And AFAIK, there are some on-going discussions about EOL of RHEL8 soon too.

check_pgbackrest `2.4` is there to fix the versioning policy change with pgBackRest `2.52.1`, which won't affect users on RHEL7 if they can't install higher version than `2.51`. So using check_pgbackrest `2.3` there should be fine.

Although, I don't maintain the YUM PGDG repos and this might sound better to ping the maintainers about it. Suggesting to remove 2.4 from the RHEL7 repos would make sense probably.

Kind Regards

**Comment by pgstef** [comment]
Added a [note](https://redmine.postgresql.org/issues/8015#note-2) on the packagers issue tracker, so closing this issue.

**Comment by m-borger** [comment]
Final note: the incompatibility was fixed by the repository maintainer by removing the 2.4 version.
