### ISSUE TITLE
200K WAL archives and intermittent "min WAL is not the oldest archive" or "max WAL is not the latest archive"

### ISSUE THREAD

**Issue by s2156945** [pgstef/check_pgbackrest#39]
Been loving your check all day since I found it.

Have two pretty active databases, we keep backups for a month, full backup every day per server, and diffs 3 times and incr every other hour.

- on one - currently that is more than 200,000 WAL files, about 10/minute.
- on the other, recently split from the first, it's only been going 10 days, 3,500 WALs.

Our config is 2 pairs of postgres clusters / 2 repos per cluster.

More often than not, the archives service comes back with one of two warnings:

- "min WAL is not the oldest archive"; OR
- "max WAL is not the latest archive"

Possibly I have 2 issues, each with a work-around...

1.  in the 200K WAL stanza, it takes a 60-120 seconds to do the pgbackrest repo-ls , so in that time some more WAL archives are likely to show up, leading to "max WAL is not the latest archive"
2. in the smaller stanza, the backups have not been around for the "backup retention period" - so there are archives older than the oldest backup

A work-around to (1) which seems to be working is --ignore-archived-after 0m - perhaps this should be the default?

```# time ./check_pgbackrest -S vz1prd -s archives --repo 1 --ignore-archived-after 0m --debug
DEBUG: pgBackRest info command was : 'pgbackrest info --stanza=vz1prd --output=json --log-level-console=error --repo=1'
DEBUG: !> pgBackRest info took 0s
DEBUG: Get all the WAL archives and history files...
DEBUG: repo1, archives_dir: archive/vz1prd/13-1
DEBUG: pgBackRest version command was : 'pgbackrest version'
DEBUG: pgBackRest ls command was : 'pgbackrest repo-ls --stanza=vz1prd archive/vz1prd/13-1 --output=json --log-level-console=error --repo=1 --recurse'
DEBUG: ignored file 00000003000003FE00000095-350b7082d09679078c0e8558cf3879235b3ba204.gz as interval since epoch : -38s
DEBUG: ignored file 00000003000003FE00000090-8ae5dd7c5267145eb1d9ee98df6bd2eaf38093c3.gz as interval since epoch : -15s
DEBUG: ignored file 00000003000003FE00000093-e6713219fbbcc37d6df474a23981868d7ad5a6c3.gz as interval since epoch : -21s
DEBUG: ignored file 00000003000003FE00000097-6311eca63585c444cb65d45a869c632c4bf6053f.gz as interval since epoch : -55s
DEBUG: ignored file 00000003000003FE00000091-aeac96a3a954a7bc6f2443141ad4eb158d387495.gz as interval since epoch : -17s
DEBUG: ignored file 00000003000003FE00000096-e73d30b04f06f716b3781f16e0fe5a2e50d697be.gz as interval since epoch : -44s
DEBUG: ignored file 00000003000003FE00000094-d8dfa9d43ad6967e6dec8da9c46cdd4629e945f4.gz as interval since epoch : -23s
DEBUG: ignored file 00000003000003FE0000008F-64b5b9318576b187e22b7f8c91add0caa1dea9d3.gz as interval since epoch : -13s
DEBUG: ignored file 00000003000003FE00000098-375f64740d0da44c5fb2c6d91f0528c46a72cf54.gz as interval since epoch : -76s
DEBUG: ignored file 00000003000003FE00000092-1e73108b1d15514c0f80c27f95232adfa7395782.gz as interval since epoch : -19s
DEBUG: ignored file 00000003000003FE0000008E-a44adf0c7cc9c8720e7e19a6e3d73155a5906c67.gz as interval since epoch : -10s

...

WAL_ARCHIVES OK - 214386 unique WAL archived, latest archived since 2m13s | latest_archive_age=133s num_unique_archives=214386

```

For (2) the work-around to clear the error was to change the `repoN-retention-full` to a number smaller than what we had backups for and run pgbackrest expire.  This cleared out the older archives.

For both I made a change to output to see what it was looking for which didn't seem too verbose, maybe you want to do similar.

```
diff --git a/check_pgbackrest b/check_pgbackrest
index b8fd048..c40c7c7 100755
--- a/check_pgbackrest
+++ b/check_pgbackrest
@@ -1077,8 +1077,8 @@ sub check_wal_archives {
         # Check min/max exists, start = min, last = max ?
         return critical $me, ['min WAL not found: '.$min_wal] if($min_wal && ! grep( /^$min_wal$/, @filelist_simplified ));
         return critical $me, ['max WAL not found: '.$max_wal] if($max_wal && ! grep( /^$max_wal$/, @filelist_simplified ));
-        push @warn_msg, "min WAL is not the oldest archive" if($min_wal && $filelist{$first_wal_in_list}[0] lt $min_wal);
-        push @warn_msg, "max WAL is not the latest archive" if($max_wal && $filelist{$last_wal_in_list}[0] gt $max_wal);
+        push @warn_msg, "min WAL '$min_wal' is not the oldest archive '$filelist{$first_wal_in_list}[0]' / '$first_wal_in_list'" if($min_wal && $filelist{$first_wal_in_list}[0] lt $min_wal);
+        push @warn_msg, "max WAL '$max_wal' is not the latest archive '$filelist{$last_wal_in_list}[0]' / '$last_wal_in_list'" if($max_wal && $filelist{$last_wal_in_list}[0] gt $max_wal);

         my $latest_archive_age = time() - $filelist{$last_wal_in_list}[2];
         my $num_archives = scalar(@filelist_simplified);
```

**Comment by pgstef** [comment]
Hi,

> Been loving your check all day since I found it.

Thanks.

> Have two pretty active databases, we keep backups for a month, full backup every day per server, and diffs 3 times and incr every other hour.

That makes a lot of backups... Does your RTO really needs that given you probably got a replica too? Anyway, that's not the topic of this issue.

> 2. in the smaller stanza, the backups have not been around for the "backup retention period" - so there are archives older than the oldest backup

Hm, you shouldn't have errors in this case. There are a few places in the code that change the `min_wal` to `oldest_bck_archive_start` and then in the `get_archived_wal_list`, it would be ignored. You should see debug messages like:

```
DEBUG: min_wal changed to 00000002000000000000002B
...
DEBUG: ignored file 000000020000000000000029 older than 00000002000000000000002B
DEBUG: ignored file 00000002000000000000002A older than 00000002000000000000002B
```

You would only spot these extra archives with `--extended-check`, and a simple `pgbackrest expire` should remove those old archives without having to expire a backup (unless you use `repo1-retention-full-type=time`).

```
P00   INFO: [DRY-RUN] repo1: 16-1 remove archive, start = 000000020000000000000029, stop = 00000002000000000000002A
P00   INFO: [DRY-RUN] expire command end: completed successfully (10ms)
```

> 1. in the 200K WAL stanza, it takes a 60-120 seconds to do the pgbackrest repo-ls , so in that time some more WAL archives are likely to show up, leading to "max WAL is not the latest archive"

Same as above. If `repo-ls` finds more archives than the `max_wal` reported by the info command, there should be a debug message like `DEBUG: ignored file 0000000200000000000000D6 newer than 0000000200000000000000D5`.

> A work-around to (1) which seems to be working is --ignore-archived-after 0m - perhaps this should be the default?

I'd prefer to have a reliable way to ignore those archives rather than using this option.

I've spent some time again on this today and to be honest it's not an easy case to reproduce (even more in the regression tests). It would have been nice to have more examples/details of outputs when you had those issues, it would have worth a deeper investigation imo because there's already some protections for this case in the current code.

> For both I made a change to output to see what it was looking for which didn't seem too verbose, maybe you want to do similar.

If you look at the `--output=human` display (which is the one I always recommend to use when debugging something), you already get the similar info:

```
Service        : WAL_ARCHIVES
Returns        : 1 (WARNING)
Message        : min WAL is not the oldest archive
Long message   : min_wal=00000002000000000000002B
Long message   : oldest_archive=000000020000000000000029
Long message   : oldest_bck_archive_start=00000002000000000000002B
```

Which pretty much tells you what's the problem. And if you want to dig deeper, then you use the `--debug` option.

If I'd have to change the code, I'd use:

```
push @warn_msg, "min WAL '$min_wal' is not the oldest archive '$filelist{$first_wal_in_list}[0]'" if($min_wal && $filelist{$first_wal_in_list}[0] lt $min_wal);
push @warn_msg, "max WAL '$max_wal' is not the latest archive '$filelist{$last_wal_in_list}[0]'" if($max_wal && $filelist{$last_wal_in_list}[0] gt $max_wal);
```

Although, I currently don't think changing the message to `WAL_ARCHIVES WARNING - min WAL '00000002000000000000002B' is not the oldest archive '000000020000000000000029'` would be a good idea. First, I tend to avoid putting debug information in the message itself (because there are specific debug options) and also mostly because of alerts acknowledgements. You'd probably have new alerts if the message (min wal or oldest archive) changes.

Kind Regards

**Comment by s2156945** [comment]
> Hi,
> 
> > Been loving your check all day since I found it.
> 
> Thanks.

Thanks for the quick reply, sorry I could not follow suit!

 
> > Have two pretty active databases, we keep backups for a month, full backup every day per server, and diffs 3 times and incr every other hour.
> 
> That makes a lot of backups... Does your RTO really needs that given you probably got a replica too? Anyway, that's not the topic of this issue.
> 

Possibly not. Being conservative to start with, yes we do have a replica for each cluster too.

> > 2. in the smaller stanza, the backups have not been around for the "backup retention period" - so there are archives older than the oldest backup
> 
> Hm, you shouldn't have errors in this case. There are a few places in the code that change the `min_wal` to `oldest_bck_archive_start` and then in the `get_archived_wal_list`, it would be ignored. You should see debug messages like:
> 
> ```
> DEBUG: min_wal changed to 00000002000000000000002B
> ...
> DEBUG: ignored file 000000020000000000000029 older than 00000002000000000000002B
> DEBUG: ignored file 00000002000000000000002A older than 00000002000000000000002B
> ```
> 
> You would only spot these extra archives with `--extended-check`, and a simple `pgbackrest expire` should remove those old archives without having to expire a backup (unless you use `repo1-retention-full-type=time`).
> 
> ```
> P00   INFO: [DRY-RUN] repo1: 16-1 remove archive, start = 000000020000000000000029, stop = 00000002000000000000002A
> P00   INFO: [DRY-RUN] expire command end: completed successfully (10ms)
> ```
> 

We do use `repo1-retention-full-type=time`, it seemed to make more sense when we were starting out, I didn't want to lose rewind distance by doing manual backups.

> > 1. in the 200K WAL stanza, it takes a 60-120 seconds to do the pgbackrest repo-ls , so in that time some more WAL archives are likely to show up, leading to "max WAL is not the latest archive"
> 
> Same as above. If `repo-ls` finds more archives than the `max_wal` reported by the info command, there should be a debug message like `DEBUG: ignored file 0000000200000000000000D6 newer than 0000000200000000000000D5`.
> 
> > A work-around to (1) which seems to be working is --ignore-archived-after 0m - perhaps this should be the default?
> 
> I'd prefer to have a reliable way to ignore those archives rather than using this option.
> 
> I've spent some time again on this today and to be honest it's not an easy case to reproduce (even more in the regression tests). It would have been nice to have more examples/details of outputs when you had those issues, it would have worth a deeper investigation imo because there's already some protections for this case in the current code.
> :set bg=dark


My reading of the code for the archive service:
- get pgbackrest info in JSON
- set min_wal + max_wal to the the min + max of pgbackrest info json under archive where the repo-key matches
- get the pgbackrest repo-ls using the min_wal + max_wal for the start_tl and end_tl
- if it is not an extended check ignore files outside the min_wal + max_wal (line 890ff)

I can't really see what "--extended-check" does - am I missing something?  Should I not be using it? It's only in the code 5 times:
- pod (line 836)
- don't ignore wal's outside min+max (lines 891 + 896)
- GetOptions args (line 1307)
- specific args - to error if you give --extended-check for other services (line 1361)

Here's the full debug + human output without my "--ignore-before" work-around.  This raises a warning more often than not:

```
root@NPCMAMPRDDBS01:~ # time sudo -u icinga  '/usr/lib64/nagios/plugins/sol1/check_pgbackrest' '--extended-check' '--latest-archive-age-alert' '3h' '--prefix' 'sudo -iu postgres' '--repo' '1' '--service' 'archives' '--stanza' 'vz1prd' --output=human --debug
DEBUG: pgBackRest info command was : 'sudo -iu postgres pgbackrest info --stanza=vz1prd --output=json --log-level-console=error --repo=1'
DEBUG: !> pgBackRest info took 0s
DEBUG: Get all the WAL archives and history files...
DEBUG: repo1, archives_dir: archive/vz1prd/13-1
DEBUG: pgBackRest version command was : 'sudo -iu postgres pgbackrest version'
DEBUG: pgBackRest ls command was : 'sudo -iu postgres pgbackrest repo-ls --stanza=vz1prd archive/vz1prd/13-1 --output=json --log-level-console=error --repo=1 --recurse'
DEBUG: !> Get all the WAL archives and history files took 100s
DEBUG: List timeline switches and check boundary WALs...
DEBUG: !> List timeline switches and check boundary WALs took 0s
DEBUG: Get all the needed WAL archives...
DEBUG: !> Get all the needed WAL archives took 0s
DEBUG: !> Go through needed WAL list and check took 1s
DEBUG: Get all the needed WAL archives for 20240712-210003F...
DEBUG: Get all the needed WAL archives for 20240712-210003F_20240712-230003I...
DEBUG: Get all the needed WAL archives for 20240712-210003F_20240713-010003I...
DEBUG: Get all the needed WAL archives for 20240712-210003F_20240713-030003D...
DEBUG: Get all the needed WAL archives for 20240712-210003F_20240713-050003I...
DEBUG: Get all the needed WAL archives for 20240712-210003F_20240713-070003I...
DEBUG: Get all the needed WAL archives for 20240712-210003F_20240713-090003D...
DEBUG: Get all the needed WAL archives for 20240712-210003F_20240713-110003I...
DEBUG: Get all the needed WAL archives for 20240712-210003F_20240713-130003I...
DEBUG: Get all the needed WAL archives for 20240712-210003F_20240713-150003D...
DEBUG: Get all the needed WAL archives for 20240712-210003F_20240713-170003I...
DEBUG: Get all the needed WAL archives for 20240712-210003F_20240713-190003I...
DEBUG: Get all the needed WAL archives for 20240713-210003F...

... (lots of repetitive stuff removed)

DEBUG: Get all the needed WAL archives for 20240811-210003F_20240812-190003I...
DEBUG: Get all the needed WAL archives for 20240812-210003F...
DEBUG: Get all the needed WAL archives for 20240812-210003F_20240812-230003I...
DEBUG: Get all the needed WAL archives for 20240812-210003F_20240813-010003I...
DEBUG: Get all the needed WAL archives for 20240812-210003F_20240813-030003D...
DEBUG: Get all the needed WAL archives for 20240812-210003F_20240813-050003I...
DEBUG: Get all the needed WAL archives for 20240812-210003F_20240813-070003I...
DEBUG: Get all the needed WAL archives for 20240812-210003F_20240813-090003D...
DEBUG: Get all the needed WAL archives for 20240812-210003F_20240813-110003I...
DEBUG: Get all the needed WAL archives for 20240812-210003F_20240813-130005I...
DEBUG: !> Go through each backup, get the needed WAL and check took 0s
Service        : WAL_ARCHIVES
Returns        : 1 (WARNING)
Message        : max WAL is not the latest archive
Long message   : latest_archive_age=1m24s
Long message   : num_unique_archives=232755
Long message   : min_wal=00000003000000D0000000CD
Long message   : max_wal=000000030000045D000000EE
Long message   : latest_archive=000000030000045D000000FF
Long message   : latest_bck_archive_start=000000030000045C00000017
Long message   : latest_bck=20240812-210003F_20240813-130005I
Long message   : latest_bck_type=incr
Long message   : oldest_archive=00000003000000D0000000CD
Long message   : oldest_bck_archive_start=00000003000000D0000000CD
Long message   : oldest_bck=20240712-210003F
Long message   : oldest_bck_type=full

real    1m42.623s
user    0m25.882s
sys     0m6.860s
```


> > For both I made a change to output to see what it was looking for which didn't seem too verbose, maybe you want to do similar.
> 
> If you look at the `--output=human` display (which is the one I always recommend to use when debugging something), you already get the similar info:
> 
> ```
> Service        : WAL_ARCHIVES
> Returns        : 1 (WARNING)
> Message        : min WAL is not the oldest archive
> Long message   : min_wal=00000002000000000000002B
> Long message   : oldest_archive=000000020000000000000029
> Long message   : oldest_bck_archive_start=00000002000000000000002B
> ```
> 
> Which pretty much tells you what's the problem. And if you want to dig deeper, then you use the `--debug` option.
> 
> If I'd have to change the code, I'd use:
> 
> ```
> push @warn_msg, "min WAL '$min_wal' is not the oldest archive '$filelist{$first_wal_in_list}[0]'" if($min_wal && $filelist{$first_wal_in_list}[0] lt $min_wal);
> push @warn_msg, "max WAL '$max_wal' is not the latest archive '$filelist{$last_wal_in_list}[0]'" if($max_wal && $filelist{$last_wal_in_list}[0] gt $max_wal);
> ```
> 
> Although, I currently don't think changing the message to `WAL_ARCHIVES WARNING - min WAL '00000002000000000000002B' is not the oldest archive '000000020000000000000029'` would be a good idea. First, I tend to avoid putting debug information in the message itself (because there are specific debug options) and also mostly because of alerts acknowledgements. You'd probably have new alerts if the message (min wal or oldest archive) changes.
> 

Agreed.

cheers,
Woody

**Comment by pgstef** [comment]
> > That makes a lot of backups... Does your RTO really needs that given you probably got a replica too? Anyway, that's not the topic of this issue.
> 
> Possibly not. Being conservative to start with, yes we do have a replica for each cluster too.

Then taking incremental every hours sounds way too much imho. You should have enough with 1 full every week and 1 diff or incremental per day.
As long as you have all the WAL archives (and you definitely don't have too many of them), you'll be able to recover/perform PITR.
Restoring from an older backup simply means a slower recovery. But usually you won't recover from a backup, you'll promote your standby and only use the backups for PITR, so recovery time won't matter that much.

> We do use `repo1-retention-full-type=time`, it seemed to make more sense when we were starting out, I didn't want to lose rewind distance by doing manual backups.

Time-based retention is not that good with old archives indeed, but I don't get what you mean with your statement about rewind distance.
If you know you have 1 full backup per week, keeping 5 full backup (number of backup) is just like keeping 4 weeks of full backups (time-based).
It don't change anything, on the contrary it's easier to predict.
 
> I can't really see what "--extended-check" does - am I missing something? Should I not be using it?
> Here's the full debug + human output without my "--ignore-before" work-around. This raises a warning more often than not:

The "workaround" is not needed if you don't use extended-check. That option has specifically been added for such cases. I mean the old archives will be ignored by default if you don't use extented-check. 
So you this option shouldn't be used by default and you wouldn't have the warnings.
On the contrary, the documentation clearly states: `Use the --extended-check argument to force a full check of the found archives and raise warnings in case of inconsistencies`. So don't be surprised if it raises warnings, it has been made for that.

So your "workaround" is already in the code, you just masked it by using the extended-check.

Anyway, thanks to your output example, this confirms to me that there doesn't need any code change since you shouldn't use extended-check by default unless you're debugging something or wanting to catch the warnings. And there's also enough debug information with the human output + debug option. It's mostly a matter of using the good options combination :-)

Thanks for your report and using the tool,
Kind Regards
